In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df1 = pd.read_csv("Dataset/dataset.csv")

In [3]:
df1.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB


In [5]:
df1.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [6]:
df1["Disease"].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [54]:
df1["Disease"].nunique()

41

In [7]:
df2 = df1[
    (df1["Disease"]=="Fungal infection") |
    (df1["Disease"]=="Allergy") |
    (df1["Disease"]=="Diabetes ") |
    (df1["Disease"]=="Hypertension ") |
    (df1["Disease"]=="Malaria") |
    (df1["Disease"]=="Dengue") |
    (df1["Disease"]=="Typhoid") 
        ]
df2.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 840 entries, 0 to 4897
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     840 non-null    object
 1   Symptom_1   840 non-null    object
 2   Symptom_2   840 non-null    object
 3   Symptom_3   840 non-null    object
 4   Symptom_4   744 non-null    object
 5   Symptom_5   552 non-null    object
 6   Symptom_6   480 non-null    object
 7   Symptom_7   480 non-null    object
 8   Symptom_8   432 non-null    object
 9   Symptom_9   360 non-null    object
 10  Symptom_10  312 non-null    object
 11  Symptom_11  192 non-null    object
 12  Symptom_12  120 non-null    object
 13  Symptom_13  120 non-null    object
 14  Symptom_14  66 non-null     object
 15  Symptom_15  0 non-null      object
 16  Symptom_16  0 non-null      object
 17  Symptom_17  0 non-null      object
dtypes: object(18)
memory usage: 124.7+ KB


In [9]:
df2["Disease"].unique()

array(['Fungal infection', 'Allergy', 'Diabetes ', 'Hypertension ',
       'Malaria', 'Dengue', 'Typhoid'], dtype=object)

In [10]:
df2.isnull().sum()

Disease         0
Symptom_1       0
Symptom_2       0
Symptom_3       0
Symptom_4      96
Symptom_5     288
Symptom_6     360
Symptom_7     360
Symptom_8     408
Symptom_9     480
Symptom_10    528
Symptom_11    648
Symptom_12    720
Symptom_13    720
Symptom_14    774
Symptom_15    840
Symptom_16    840
Symptom_17    840
dtype: int64

In [11]:
df2 = df2.drop(["Symptom_5","Symptom_6","Symptom_7","Symptom_8","Symptom_9","Symptom_10","Symptom_11","Symptom_12","Symptom_13",
                "Symptom_14","Symptom_15","Symptom_16","Symptom_17"],axis=1)

In [12]:
df2.isnull().sum()

Disease       0
Symptom_1     0
Symptom_2     0
Symptom_3     0
Symptom_4    96
dtype: int64

In [13]:
df2 = df2.dropna()

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 744 entries, 0 to 4897
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Disease    744 non-null    object
 1   Symptom_1  744 non-null    object
 2   Symptom_2  744 non-null    object
 3   Symptom_3  744 non-null    object
 4   Symptom_4  744 non-null    object
dtypes: object(5)
memory usage: 34.9+ KB


In [15]:
df_sev1 = pd.read_csv("Dataset/Symptom-severity.csv")

In [16]:
df_sev1.head()

Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5

In [17]:
df_sev1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Symptom  133 non-null    object
 1   weight   133 non-null    int64 
dtypes: int64(1), object(1)
memory usage: 2.2+ KB


In [18]:
df_sev1.isnull().sum()

Symptom    0
weight     0
dtype: int64

In [19]:
df2["Disease"].value_counts()

Malaria             120
Dengue              120
Typhoid             120
Hypertension        120
Diabetes            120
Allergy              72
Fungal infection     72
Name: Disease, dtype: int64

In [20]:
df2.head()

Disease             Symptom_1     Symptom_2  \
0   Fungal infection               itching     skin_rash   
9   Fungal infection               itching     skin_rash   
10           Allergy   continuous_sneezing     shivering   
19           Allergy   continuous_sneezing     shivering   
70         Diabetes                fatigue   weight_loss   

                Symptom_3             Symptom_4  
0    nodal_skin_eruptions   dischromic _patches  
9    nodal_skin_eruptions   dischromic _patches  
10                 chills    watering_from_eyes  
19                 chills    watering_from_eyes  
70           restlessness              lethargy

In [21]:
df2["Symptom_4"].unique()

array([' dischromic _patches', ' watering_from_eyes', ' lethargy',
       ' irregular_sugar_level', ' loss_of_balance',
       ' lack_of_concentration', ' sweating', ' headache', ' vomiting',
       ' fatigue', ' high_fever'], dtype=object)

In [22]:
df_sev1[df_sev1["Symptom"]=="dischromic_patches"]

Symptom  weight
102  dischromic_patches       6

In [23]:
# df2 = df2["Symptom_1"].apply(lambda x: 1 if x == "itching" else 4 if x == (" continuous_sneezing"|" fatigue") else 3 if x == (" weight_loss"|" headache"))

In [24]:
df2["Symptom_1"] = df2["Symptom_1"].map({"itching":1," continuous_sneezing":4," fatigue":4," weight_loss":3,
                                         " headache":3," chest_pain":7," chills":3," vomiting":5," skin_rash":3
                                        })
df2["Symptom_2"] = df2["Symptom_2"].map({" skin_rash":3," shivering":5," weight_loss":3," restlessness":5,
                                         " chest_pain":7," dizziness":4," vomiting":5," high_fever":7," chills":3,
                                         " joint_pain":3," fatigue":4
                                        })
df2["Symptom_3"] = df2["Symptom_3"].map({" nodal_skin_eruptions":4," chills":3," restlessness":5," lethargy":2,
                                         " dizziness":4," loss_of_balance":4," high_fever":7," sweating":3,
                                         " joint_pain":3," vomiting":5," fatigue":4,
                                        })
df2["Symptom_4"] = df2["Symptom_4"].map({" dischromic _patches":6," watering_from_eyes":4," lethargy":2," irregular_sugar_level":5,
                                         " loss_of_balance":4," lack_of_concentration":3," sweating":3,
                                         " headache":3," vomiting":5," fatigue":4," high_fever":7
                                        })

In [25]:
df2.head()

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4
0   Fungal infection          1          3          4          6
9   Fungal infection          1          3          4          6
10           Allergy          4          5          3          4
19           Allergy          4          5          3          4
70         Diabetes           4          3          5          2

In [26]:
df2["Disease"].value_counts()

Malaria             120
Dengue              120
Typhoid             120
Hypertension        120
Diabetes            120
Allergy              72
Fungal infection     72
Name: Disease, dtype: int64

In [27]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 744 entries, 0 to 4897
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Disease    744 non-null    object
 1   Symptom_1  744 non-null    int64 
 2   Symptom_2  744 non-null    int64 
 3   Symptom_3  744 non-null    int64 
 4   Symptom_4  744 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 34.9+ KB


In [28]:
df2.isnull().sum()

Disease      0
Symptom_1    0
Symptom_2    0
Symptom_3    0
Symptom_4    0
dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X = df2.drop(["Disease"],axis=1).values

In [31]:
X

array([[1, 3, 4, 6],
       [1, 3, 4, 6],
       [4, 5, 3, 4],
       ...,
       [3, 5, 7, 3],
       [3, 3, 3, 5],
       [3, 5, 4, 7]], dtype=int64)

In [32]:
y = df2["Disease"].values

In [33]:
#y

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [45]:
rfc = RandomForestClassifier()
dtc = DecisionTreeClassifier()
lr = LogisticRegression(max_iter=1000)

In [46]:
rfc.fit(X_train,y_train)
dtc.fit(X_train,y_train)
lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [47]:
print(rfc.score(X_test,y_test))
print(dtc.score(X_test,y_test))
print(lr.score(X_test,y_test))

1.0
1.0
0.9375


In [48]:
y_pred = dtc.predict(X_test)

In [49]:
from sklearn.metrics import classification_report,confusion_matrix

In [50]:
print(classification_report(y_test,y_pred))

                  precision    recall  f1-score   support

         Allergy       1.00      1.00      1.00        18
          Dengue       1.00      1.00      1.00        43
       Diabetes        1.00      1.00      1.00        35
Fungal infection       1.00      1.00      1.00        18
   Hypertension        1.00      1.00      1.00        37
         Malaria       1.00      1.00      1.00        42
         Typhoid       1.00      1.00      1.00        31

        accuracy                           1.00       224
       macro avg       1.00      1.00      1.00       224
    weighted avg       1.00      1.00      1.00       224



In [51]:
print(confusion_matrix(y_test,y_pred))

[[18  0  0  0  0  0  0]
 [ 0 43  0  0  0  0  0]
 [ 0  0 35  0  0  0  0]
 [ 0  0  0 18  0  0  0]
 [ 0  0  0  0 37  0  0]
 [ 0  0  0  0  0 42  0]
 [ 0  0  0  0  0  0 31]]


In [52]:
filename = 'random_forest.sav'
pickle.dump(rfc, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
result

1.0

In [53]:
rfc.predict([[9,2,3,4]])

array(['Diabetes '], dtype=object)